### ISSUE TITLE
Dear authors, How many hours did you take to run each environment?

### ISSUE THREAD

**Issue by GoingMyWay** [MouseHu/GEM#1]
Dear authors, 

How many hours did you take to run each environment? For example on RTX 3090, how many hours, GPU memories and GPU memories do you need to run each environment?

Best regards.

**Comment by MouseHu** [comment]
For mujoco tasks, the experiments were run on GTX 1080Ti, and it took roughly 10 hours for 1M steps with 5 seeds running on the same card. Each seed consumes ~500 MB GPU memories,  which is the same as TD3.

**Comment by GoingMyWay** [comment]
> 

Thanks. Did Atari tasks take 10 hours?

**Comment by HeavyCrab** [comment]
> 

It took roughly 15 hrs for 1M steps with 4 seeds running on the same card. Each seed consumes ~2000MB GPU memories.

**Comment by GoingMyWay** [comment]
> 

Thank you for your answer. 👍
